---
sudo: false
language: node_js
rvm:
  - 2.2.0
node_js:
  - 0.12.7
before_install:
  - gem update --system
  - gem install bundler
  - bundle install --path=vendor/bundle
  - npm install -g bower grunt-cli
  - bower install
cache: bundler
script: grunt
notifications:
  email: false
